### ISSUE TITLE
Installation and Update script

### ISSUE THREAD

**Issue by ghost** [johncorderox/Colorful-Tasks#29]
Hi @johncorderox ,

I am really happy somebody is taking time on developing this application, could I ask if you please provide an installation and update script.

Please see example below 👍 

https://github.com/panique/huge/blob/master/_one-click-installation/bootstrap.sh

Thanks for epic app!

**Comment by ghost** [comment]
@johncorderox And if you don't have any time I am more than willing to create one for you.

**Comment by johncorderox** [comment]
not needed but on its the 'list' of future potential updates. thank you
