### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by ghost** [johncorderox/Colorful-Tasks#30]
Hi @johncorderox,

I have noticed this application has a couple of security holes may I suggest you migrate to https://github.com/panique/huge

**Comment by johncorderox** [comment]
Thank you @di48l069 Ill take a look at it later this week. I didn't think this application would get popular for people to care enough.

**Comment by ghost** [comment]
@johncorderox Yes has a lot of potential I have been using it! Would be interesting to migrate to HUGE framework then you have a epic UI with epic functionality mixed with really good security.

**Comment by johncorderox** [comment]
Security is priority for now. but I'm making some docs for the app and cleaning up some coveralls suggestions. Ill check out improved security soon. thanks for using it. tell your friends. ha.

**Comment by ghost** [comment]
@johncorderox Will do
